import { mainRoute } from "../static/endpoints";

export const routes = {
  MAIN: mainRoute.MAIN,
  SIGN_UP: mainRoute.SIGN_UP,
  SIGN_IN: mainRoute.SIGN_IN,
  LOGOUT: mainRoute.LOGOUT,
  ABOUT_US: mainRoute.ABOUT_US,
  MOST_ORDERED: mainRoute.MOST_ORDERED,
  ADMIN_DASHBOARD: mainRoute.ADMIN_DASHBOARD,
  ADMIN_DASHBOARD_CREATE_PACKAGE: mainRoute.ADMIN_DASHBOARD_CREATE_PACKAGE,
  ADMIN_DASHBOARD_CREATE_RESTAURANT:
    mainRoute.ADMIN_DASHBOARD_CREATE_RESTAURANT,
  ADMIN_DASHBOARD_CREATE_MENU: mainRoute.ADMIN_DASHBOARD_CREATE_MENU,
  ADMIN_DASHBOARD_CREATE_LOCATION: mainRoute.ADMIN_DASHBOARD_CREATE_LOCATION,
  ADMIN_DASHBOARD_CREATE_CATEGORY: mainRoute.ADMIN_DASHBOARD_CREATE_CATEGORY,
  ADMIN_DASHBOARD_CREATE_MEAL: mainRoute.ADMIN_DASHBOARD_CREATE_MEAL,
  RESTAURANTS: mainRoute.RESTAURANTS,
  RESTAURANTS_UPDATE: mainRoute.RESTAURANTS_UPDATE,
  MENU: mainRoute.MENU,
  MENU_UPDATE: mainRoute.MENU_UPDATE,
  MEAL: mainRoute.MEAL,
  MEAL_UPDATE: mainRoute.MEAL_UPDATE,
  ORDER: mainRoute.ORDER,
  ORDER_UPDATE: mainRoute.ORDER_UPDATE,
  CATEGORY: mainRoute.CATEGORY,
  LOCATION: mainRoute.LOCATION,
  PACKAGE: mainRoute.PACKAGE,
  PROFILE: mainRoute.PROFILE,
  NOT_FOUND: mainRoute.NOT_FOUND,
};

