export const inputsCreateMealData = [
  {
    htmlFor: "name",
    labelTitle: "Name:",
    type: "text",
    name: "name",
    placeholder: "Enter your name...",
  },
  {
    htmlFor: "picture",
    labelTitle: "Image url:",
    type: "text",
    name: "picture",
    placeholder: "Enter your image url...",
  },
  {
    htmlFor: "description",
    labelTitle: "Description:",
    type: "text",
    name: "description",
    placeholder: "Enter your description...",
  },
  {
    htmlFor: "startDate",
    labelTitle: "Start date:",
    type: "date",
    name: "startDate",
    placeholder: "Enter your start date...",
  },
  {
    htmlFor: "endDate",
    labelTitle: "End date:",
    type: "date",
    name: "endDate",
    placeholder: "Enter your end date...",
  },
  {
    htmlFor: "startHour",
    labelTitle: "Start hour:",
    type: "time",
    name: "startHour",
    placeholder: "Enter your start hour...",
  },
  {
    htmlFor: "endHour",
    labelTitle: "End hour:",
    type: "time",
    name: "endHour",
    placeholder: "Enter your end hour...",
  },
  {
    htmlFor: "price",
    labelTitle: "Price:",
    type: "number",
    name: "price",
    placeholder: "Enter price...",
  },
  {
    htmlFor: "weight",
    labelTitle: "Weight:",
    type: "number",
    name: "weight",
    placeholder: "Enter weight...",
  },
];
